pokemon_go = ['Clodsire', 'Diggersby', 'Forretress', 'Lapras', 'Jellicent', 'Corsola (Galarian)', 'Dusclops',
'Samurott', 'Gligar', 'Clodsire', 'Feraligatr', 'Golisopod', 'Mandibuzz', 'Corviknight', 'Gastrodon',
'Steelix', 'Stunfisk', 'Dusknoir', 'Carbink', 'Dedenne', 'Morpeko (Full Belly)', 'Togedemaru', 'Cradily',
'Marowak', 'Primeape', 'Furret', 'Pangoro', 'Bastiodon', 'Emolga', 'Runerigus', 'Azumarill', 'Grumpig',
'Quagsire', 'Sableye', 'Bellibolt', 'Dragalge', 'Malamar', 'Araquanid', 'Claydol', 'Metang', 'Moltres (Galarian)',
'Tinkaton', 'Toxapex', 'Aurorus', 'Togetic', 'Weezing (Galarian)', 'Regidrago', 'Drifblim', 'Melmetal',
'Golurk', 'Jumpluff', 'Marowak (Alolan)', 'Scizor', 'Blastoise', 'Clefable', 'Lickitung', 'Annihilape',
'Bronzong', 'Sandslash (Alolan)', 'Victreebel', 'Golisopod', 'Lurantis', 'Swampert', 'Whiscash', 'Greninja',
'Machamp', 'Vespiquen', 'Guzzlord', 'Registeel', 'Tinkatuff', 'Dewott', 'Armarouge', 'Linoone', 'Drapion', 'Tentacruel',
'Gliscor', 'Hakamo-o', 'Raichu', 'Wigglytuff', 'Dunsparce', 'Medicham', 'Goodra', 'Dachsbun', 'Stunfisk (Galarian)', 
'Swalot', 'Talonflame', 'Froslass', 'Pachirisu', 'Wormadam (Trash)', 'Lanturn', 'Lickilicky', 'Hippopotas', 'Lairon', 
'Nidoqueen', 'Spiritomb', 'Ninetales', 'Regirock', 'Qwilfish', 'Thievul', 'Skeledirge', 'Electrode (Hisuian)', 
'Ninetales (Alolan)', 'Barbaracle', 'Hippowdon', 'Sealeo', 'Serperior', 'Zapdos', 'Amoonguss', 'Klefki', 'Toxicroak', 
'Dewgong', "Farfetch'd (Galarian)", 'Donphan', 'Aron', 'Dragonair', 'Toxtricity', 'Magnezone', 'Walrein', "Farfetch'd", 
'Florges', 'Magcargo', 'Bellossom', 'Mew', "Sirfetch'd", 'Ledian', 'Electivire', 'Kommo-o', 'Skarmory', 'Dragonite', 
'Castform (Sunny)', 'Genesect', 'Zweilous', 'Arctibax', 'Charjabug', 'Qwilfish (Hisuian)', 'Urshifu (Single Strike)', 
'Chesnaught', 'Gogoat', 'Ursaring', 'Venusaur', 'Gourgeist (Super)', 'Marshtomp', 'Meganium', 'Umbreon', 'Glalie', 'Piloswine', 
'Crustle', 'Salazzle', 'Machoke', 'Miltank', 'Altaria', 'Castform (Rainy)', 'Giratina (Origin)', 'Spinda', 'Gallade', 'Sandslash', 
'Cofagrigus', 'Tropius', 'Raichu (Alolan)', 'Dragapult', 'Mightyena', 'Cetoddle', 'Nidorina', 'Oranguru', 'Wailmer', 'Whimsicott', 
'Ferrothorn', 'Gourgeist (Large)', 'Mantine', 'Suicune', 'Cresselia', 'Trevenant', 'Aggron', 'Pumpkaboo (Super)', 'Relicanth', 
'Wailord', 'Gengar', 'Lileep', 'Bombirdier', 'Fletchinder', 'Gourgeist (Average)', 'Greedent', 'Overqwil', 'Tauros (Aqua)', 
'Wartortle', 'Abomasnow', 'Castform', 'Cetitan', 'Pawniard', 'Typhlosion', 'Lokix', 'Roserade', 'Samurott (Hisuian)', 
'Decidueye', 'Haunter', 'Leavanny', 'Kingambit', 'Perrserker', 'Skuntank', 'Beedrill', 'Empoleon', 'Amaura', 'Ariados', 
'Hariyama', 'Hydreigon', 'Poliwrath', 'Kricketune', 'Venomoth', 'Drampa', 'Gourgeist (Small)', 'Scrafty', 'Starmie', 
'Grimer (Alolan)', 'Gyarados', 'Avalugg', 'Raikou', 'Scyther', 'Drifloon', 'Galvantula', 'Litleo', 'Servine', 'Castform (Snowy)', 
'Pelipper', 'Dugtrio (Alolan)', 'Magneton', 'Flygon', 'Pawmot', 'Turtonator', 'Golett', 'Frillish', 'Furfrou', 'Grimer', 'Hawlucha', 
'Pidgeot', 'Oinkologne (Female)', 'Dubwool', 'Pumpkaboo (Large)', 'Raticate (Alolan)', 'Regice', 'Arcanine', 'Bewear', 
'Sneasler', 'Charizard', 'Machop', 'Lucario', 'Pawmo', 'Zangoose', 'Mantyke', 'Rapidash (Galarian)', 'Sylveon', 
'Tapu Fini', 'Ampharos', 'Aromatisse', 'Rapidash', 'Rhyperior', 'Grafaiai', 'Politoed', 'Mawile', 'Typhlosion (Hisuian)', 
'Kangaskhan', 'Sceptile', 'Vaporeon', 'Escavalier', 'Bibarel', 'Kleavor', 'Magmar', 'Munchlax', 'Centiskorch', 
'Golem (Alolan)', 'Pinsir', 'Armaldo', 'Celesteela', 'Crocalor', 'Mamoswine', 'Noctowl', 'Druddigon', 'Spritzee', 
'Heliolisk', 'Staravia', 'Dugtrio', 'Magmortar', 'Pumpkaboo (Average)', 'Snorlax', 'Avalugg (Hisuian)', 'Klang', 'Muk', 
'Passimian', 'Rhydon', 'Slowking (Galarian)', 'Parasect', 'Excadrill', 'Magnemite', 'Primarina', 'Tauros (Combat)', 
'Fraxure', 'Heatran', 'Kecleon', 'Mienshao', 'Obstagoon', 'Seaking', 'Tyrunt', 'Articuno (Galarian)', 'Palossand', 
'Sandshrew (Alolan)', 'Thundurus (Incarnate)', 'Togekiss', 'Vullaby', 'Deoxys (Defense)', 'Zygarde (50% Forme)', 
'Golbat', 'Staraptor', 'Sandshrew', 'Dhelmise', 'Braixen', 'Gholdengo', 'Girafarig', 'Drilbur', 'Hypno', 'Ivysaur', 
'Lunatone', 'Jirachi', 'Incineroar', 'Slowbro (Galarian)', 'Graveler (Alolan)', 'Hitmontop', 'Muk (Alolan)', 'Pyroar', 
'Bruxish', 'Golem', 'Lugia', 'Scolipede', 'Baxcalibur', 'Pumpkaboo (Small)', 'Houndstone', 'Solrock', 'Chansey', 'Chimecho', 
'Dartrix', 'Granbull', 'Quilladin', 'Alomomola', 'Haxorus', 'Misdreavus', 'Aipom', 'Ninjask', 'Conkeldurr', 'Probopass', 
'Shiftry', 'Slurpuff', 'Sneasel (Hisuian)', 'Torkoal', 'Ho-Oh', 'Leafeon', 'Uxie', 'Victini', 'Cryogonal', 'Grovyle', 
'Kabuto', 'Oinkologne', 'Shiinotic', 'Poliwhirl', 'Manectric', 'Swoobat', 'Golduck', 'Cacturne', 'Durant', 'Krookodile', 
'Magby', 'Milotic', 'Rhyhorn', 'Tauros (Blaze)', 'Wormadam (Sandy)', 'Rayquaza', 'Naganadel', 'Electabuzz', 'Stoutland', 
'Basculin', 'Palpitoad', 'Rufflet', 'Quaquaval', 'Bayleef', 'Purugly', 'Blaziken', 'Frigibax', 'Meowscarada', 'Corsola', 
'Krokorok', 'Swadloon', 'Tangrowth', 'Pignite', 'Luxray', 'Nidoking', 'Vigoroth', 'Dolliv', 'Eelektrik', 'Maushold', 
'Weezing', 'Ceruledge', 'Floette', 'Wobbuffet', 'Karrablast', 'Vikavolt', 'Darumaka', 'Seviper', 'Buzzwole', 
'Crawdaunt', 'Ponyta', 'Combusken', 'Charmeleon', 'Croconaw', 'Latios', 'Lopunny', 'Lumineon', 'Quaxwell', 'Eelektross', 
'Ludicolo', 'Articuno', 'Electrode', 'Huntail', 'Gardevoir', 'Gloom', 'Kabutops', 'Seismitoad', 'Skrelp', 'Bonsly', 
'Kingdra', 'Scraggy', 'Hitmonlee', 'Regieleki', 'Landorus (Incarnate)', 'Prinplup', 'Smoochum', 'Volcanion', 'Cubone', 
'Nidorino', 'Corvisquire', 'Hatterene', 'Shelgon', 'Urshifu (Rapid Strike)', 'Vanillish', 'Hitmonchan', 'Salamence', 
'Arbok', 'Darmanitan (Standard)', 'Growlithe', 'Zapdos (Galarian)', 'Beartic', 'Heatmor', 'Sandygast', 'Floatzel', 
'Rotom', 'Geodude (Alolan)', 'Elekid', 'Gigalith', 'Buneary', 'Herdier', 'Weepinbell', 'Crobat', 'Flareon', 'Jolteon', 
'Linoone (Galarian)', 'Monferno', 'Vileplume', 'Bisharp', 'Bouffalant', 'Oddish', 'Omanyte', 'Minun', 'Moltres', 
'Cloyster', 'Emboar', 'Falinks', 'Shellos', 'Torracat', 'Stakataka', 'Darumaka (Galarian)', 'Drakloak', 'Exploud', 
'Growlithe (Hisuian)', 'Klinklang', 'Mismagius', 'Kartana', 'Poipole', 'Delcatty', 'Appletun', 'Quilava', 'Grotle', 
'Vibrava', 'Heracross', 'Houndoom', 'Rotom (Heat)', 'Ursaluna', 'Diancie', 'Frogadier', 'Carnivine', 'Chandelure', 
'Graveler', 'Gurdurr', 'Slowbro', 'Slowking', 'Tirtouga', 'Yanmega', 'Delphox', 'Garchomp', 'Mankey', 'Porygon', 
'Arboliva', 'Raboot', 'Zoroark', 'Entei', 'Kubfu', 'Swanna', 'Camerupt', 'Larvesta', 'Swellow', 'Torterra', 'Slowpoke', 
'Eldegoss', 'Mr. Mime', 'Sneasel', 'Thwackey', 'Wormadam (Plant)', 'Breloom', 'Comfey', 'Tauros', 'Cherrim (Sunshine)', 
'Blissey', 'Metagross', 'Oricorio (Sensu)', 'Tyrantrum', 'Flapple', 'Oricorio (Pom-Pom)', 'Geodude', 
'Arcanine (Hisuian)', 'Luxio', 'Cursola', 'Rillaboom', 'Weavile', 'Infernape', 'Mothim', 'Oricorio (Baile)', 'Simisage', 
'Slowpoke (Galarian)', 'Tangela', 'Aerodactyl', 'Stufful', 'Wyrdeer', 'Decidueye (Hisuian)', 'Nuzleaf', 'Honchkrow', 
'Porygon2', 'Teddiursa', 'Pidgeotto', 'Sudowoodo', 'Onix', 'Sliggoo', 'Sharpedo', 'Dustox', 'Fuecoco', 'Shaymin (Land)', 
'Tsareena', 'Rotom (Wash)', 'Zygarde (10% Forme)', 'Archeops', 'Boldore', 'Gabite', 'Ambipom', 'Latias', 'Banette', 
'Lycanroc (Dusk)', 'Polteageist', 'Tyranitar', 'Seel', 'Absol', 'Braviary', 'Simisear', 'Brionne', 'Cinderace', 
'Clamperl', 'Exeggutor (Alolan)', 'Houndour', 'Lycanroc (Midday)', 'Lycanroc (Midnight)', 'Yanma', 'Espurr', 'Revavroom', 
'Sawk', 'Masquerain', 'Carracosta', 'Popplio', 'Vivillon', 'Raticate', 'Ribombee', 'Stonjourner', 'Espeon', 'Glaceon', 
'Hattrem', 'Zebstrika', 'Vanilluxe', 'Darmanitan (Galarian)', 'Kingler', 'Stunky', 'Cinccino', 'Meowstic (Male)', 
'Mesprit', 'Murkrow', 'Tranquill', 'Archen', 'Lombre', 'Pineco', 'Celebi', 'Gothitelle', 'Persian (Alolan)', 
'Rotom (Mow)', 'Sigilyph', 'Simipour', 'Skorupi', 'Phanpy', 'Plusle', 'Rotom (Frost)', 'Trapinch', 'Corphish', 
'Persian', 'Dwebble', 'Omastar', "Oricorio (Pa'u)", 'Stantler', 'Wugtrio', 'Lampent', 'Clauncher', 'Crabominable',
'Mr. Rime', 'Chinchou', 'Gothorita', 'Tentacool', 'Toucannon', 'Sunflora', 'Whirlipede', 'Totodile', 'Beautifly', 
'Crabrawler', 'Fearow', 'Eevee', 'Loudred', 'Butterfree', 'Flaaffy', 'Lilligant', 'Chespin', 'Drizzile', 'Bulbasaur',
'Ponyta (Galarian)', 'Boltund', 'Dodrio', 'Illumise', 'Meowstic (Female)', 'Alakazam', 'Braviary (Hisuian)', 'Snover', 
'Krabby', 'Musharna', 'Floragato', 'Gumshoos', 'Liepard', 'Mr. Mime (Galarian)', 'Koffing', 'Pancham', 'Komala', 
'Garbodor', 'Goldeen', 'Watchog', 'Sawsbuck', 'Exeggcute', 'Hoopa', 'Azelf', 'Piplup', 'Maractus', 'Nosepass', 
'Exeggutor', 'Rampardos', 'Octillery', 'Xatu', 'Bergmite', 'Clawitzer', 'Deerling', 'Shaymin (Sky)', 'Pupitar', 
'Beheeyem', 'Inteleon', 'Trumbeak', 'Drowzee', 'Roggenrola', 'Volbeat', 'Roselia', 'Elgyem', 'Gorebyss', 'Audino', 
'Seadra', 'Jynx', 'Varoom', 'Accelgor', 'Cherrim (Overcast)', 'Flabebe', 'Rowlet', 'Porygon-Z', 'Throh', 'Turtwig', 
'Noivern', 'Chatot', 'Reuniclus', 'Meltan', 'Axew', 'Ferroseed', 'Swirlix', 'Unfezant', 'Tornadus (Incarnate)', 'Timburr', 
'Snubbull', 'Deoxys (Speed)', 'Munna', 'Duosion', 'Solosis', 'Anorith', 'Skiddo', 'Spoink', 'Clefairy', 'Kadabra', 'Unown', 
'Mienfoo', 'Slaking']
