name: pokemon_go_battle_assistant
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - jupyterlab
  - pandas
  - python=3.10
  - scikit-learn
  - scikit-plot
  - seaborn
  - pip
  - pip:
      - python-dotenv
      - ydata-profiling
      - scrapy
      - selenium
      - beautifulsoup4
<<<<<<< HEAD
      - pandas
=======
>>>>>>> image_database
      - imagehash
      - duckduckgo-search
      - pillow
      - requests
      - tensorflow
      - PyQt5
<<<<<<< HEAD
      - torch
      - streamlit
      - catboost
=======
      - torch
>>>>>>> image_database
